server:
  address: localhost
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://sos.cwsbydbncjrx.ap-northeast-2.rds.amazonaws.com/sos
    username: admin
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      hibernate:
#        ddl-auto: create-drop
#    generate-ddl: true